spring:
  application:
    name: yaak

  # default active profile
  profiles:
    active: sandbox

server:
  port: 8080

logging:
  level:
    sun.net: DEBUG
    org.springframework.web: INFO
    com.dietmap: INFO