appstore:
  base-url: https://buy.itunes.apple.com

userapp:
  # called when the /api/receipt/verify endpoint is called
  receipt-validate-webhook-url: http://localhost:8080/handle
  # called when the /api/subscription/statusUpdateNotification endpoint is called
  subscription-update-webhook-url: http://localhost:8080/handle