spring:
  application:
    name: yaak-api
  profiles:
    active: sandbox
  output:
    ansi:
      enabled: always

logging:
  level:
    sun.net: INFO
    org.springframework.web: INFO
    com.dietmap: INFO