name: Build docker image

on: [push]
#on:
#  push:
#    tags:
#      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build & push docker image
#        env:
#          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#        run: ./gradlew jib
      - name: Call webhook
        run: |
          IMAGE_TAG=$(./gradlew cV -q -Prelease.quiet)
          curl -s -o /dev/null -w "%{http_code}" -X POST -F token=${{ secrets.WEBHOOK_TOKEN }} -F "ref=master" -F "variables[IMAGE_TAG]=$IMAGE_TAG"  ${{ secrets.WEBHOOK_URL }}
